# SPDX-FileCopyrightText: 2021 Kirill Elagin <https://kir.elagin.me>
#
# SPDX-License-Identifier: MPL-2.0

name: cerise
version: 0.0.0.1
synopsis: Coupled relational symbolic execution (_CRSE_) analysis for differential privacy.
description: |
  TBD
category: Privacy

author: Kirill Elagin <kir@elagin.me>
copyright: 2021 Kirill Elagin
license-file: LICENSES/MPL-2.0.txt

extra-doc-files:
  - CHANGELOG.md
  - README.md


dependencies:
  - base >= 4.7 && < 4.15
  - bytestring >= 0.9 && < 0.11
  - safe-exceptions >= 0.1 && < 0.2


library:
  source-dirs: lib

  dependencies:
    []

tests:
  cerise-lib-test:
    source-dirs: test/cerise-lib
    main: Main.hs

    dependencies:
      - cerise

      - hedgehog
      - HUnit
      - tasty
      - tasty-hedgehog
      - tasty-hunit

      - deepseq

    build-tools:
      - tasty-discover:tasty-discover


ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints

default-extensions:
  - BangPatterns
  - ConstraintKinds
  - DataKinds
  - DefaultSignatures
  - DeriveDataTypeable
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - MultiWayIf
  - NamedFieldPuns
  - NumericUnderscores
  - OverloadedStrings
  - OverloadedLabels
  - PatternSynonyms
  - PolyKinds
  - RankNTypes
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - UndecidableInstances
  - ViewPatterns
